// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListJobsRequest {
    /** Maximum number of jobs to return. */
    limit?: number;
    /** Opaque cursor for the next page of results. */
    nextToken?: string;
    /** Return the matching job identifier, if it belongs to the account. */
    jobId?: string;
    /** Filter jobs by processing mode. */
    mode?: SegmentationAPI.ProcessingMode;
    /** Filter jobs by status. */
    status?: SegmentationAPI.JobStatus;
}
