// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         jobId: "jobId"
 *     }
 */
export interface RetrieveJobRequest {
    /** Async job identifier. */
    jobId: string;
}
