// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as SegmentationAPI from "../index.js";

export class BadGatewayError extends errors.SegmentationAPIError {
    public declare readonly body: SegmentationAPI.ApiError;

    constructor(body: SegmentationAPI.ApiError, rawResponse?: core.RawResponse) {
        super({
            message: "BadGatewayError",
            statusCode: 502,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "BadGatewayError";
    }
}
