// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key"
 *     }
 */
export interface CreateCheckoutRequest {
    "Idempotency-Key": string;
}
