// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         label: "label"
 *     }
 */
export interface CreateApiKeyRequest {
    "Idempotency-Key": string;
    label: string;
}
