// This file was auto-generated by Fern from our API Definition.

export interface AccessOverview {
    mode: AccessOverview.Mode;
    reason: AccessOverview.Reason;
    canCreateJobs: boolean;
    videoAllowed: boolean;
    downloadsAllowed: boolean;
    maxImageTasksPerJob: number;
    maxActiveJobs: number;
}

export namespace AccessOverview {
    export const Mode = {
        Paid: "paid",
        Trial: "trial",
        Blocked: "blocked",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    export const Reason = {
        PaidAccess: "paid_access",
        TrialEligible: "trial_eligible",
        TrialActive: "trial_active",
        TrialExhausted: "trial_exhausted",
        TrialExpired: "trial_expired",
        BillingDelinquent: "billing_delinquent",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
}
