// This file was auto-generated by Fern from our API Definition.

export interface Account {
    accountId: string;
    email: string;
    emailVerified: boolean;
    image?: (string | null) | undefined;
    name: string;
    status: string;
}
