// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface AccountOverview {
    tokenUsageLast24h: number;
    billing: SegmentationApi.BillingOverview;
    access: SegmentationApi.AccessOverview;
    trial: SegmentationApi.TrialOverview;
}
