// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export interface AccountOverview {
    tokenUsageLast24h: number;
    billing: SegmentationAPI.BillingOverview;
    access: SegmentationAPI.AccessOverview;
    trial: SegmentationAPI.TrialOverview;
}
