// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    error: string;
    message?: string | undefined;
    remainingTokens?: number | undefined;
    requestedTokens?: number | undefined;
    expiresAt?: string | undefined;
    activeJobId?: string | undefined;
    upgradeUrl?: string | undefined;
    retryAfterSeconds?: number | undefined;
}
