// This file was auto-generated by Fern from our API Definition.

export interface ApiKey {
    keyId: string;
    label: string;
    prefix: string;
    revoked: boolean;
    revokedAt?: (string | null) | undefined;
    createdAt: string;
    updatedAt: string;
}
