// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface AsyncAcceptedResponse {
    jobId: string;
    type: AsyncAcceptedResponse.Type;
    totalItems: number;
    trial?: SegmentationApi.TrialAcceptedOverview | undefined;
}

export namespace AsyncAcceptedResponse {
    export const Type = {
        Image: "image",
        Video: "video",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
