// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export interface AsyncJobStatusResponse {
    jobId: string;
    type: AsyncJobStatusResponse.Type;
    processingMode: SegmentationAPI.ProcessingMode;
    status: SegmentationAPI.JobStatus;
    totalItems: number;
    createdAt: string;
    updatedAt: string;
    error?: (string | null) | undefined;
    /** Per-task results for the job */
    tasks: SegmentationAPI.JobTaskStatus[];
}

export namespace AsyncJobStatusResponse {
    export const Type = {
        Image: "image",
        Video: "video",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
