// This file was auto-generated by Fern from our API Definition.

export interface BillingOverview {
    accessStatus?: string | undefined;
    currentPeriodEnd?: string | undefined;
    latestInvoiceStatus?: string | undefined;
    stripeSubscriptionStatus?: string | undefined;
}
