// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface CreateApiKeyResponse extends SegmentationApi.ApiKeyMutation {
    secret?: string | undefined;
    secretUnavailable: boolean;
}
