// This file was auto-generated by Fern from our API Definition.

export interface ImageJobCreateRequest {
    /** Required for all jobs and must include at least one non-empty prompt. */
    prompts: string[];
    /** When true, includes a composited preview image in the result. */
    generatePreview?: boolean | undefined;
    /** Confidence threshold. Defaults to 0.5. */
    threshold?: number | undefined;
    /** Mask threshold. Defaults to 0.5. */
    maskThreshold?: number | undefined;
    /** Task ids returned by POST /v1/uploads/presign. */
    tasks: string[];
}
