// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface ImageOutputItem {
    taskId: string;
    inputId: string;
    units: number;
    generatedAt: string;
    previewUrl?: string | undefined;
    masks: SegmentationApi.ImageMask[];
}
