// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export type JobCreateRequest = SegmentationAPI.JobCreateRequest.Image | SegmentationAPI.JobCreateRequest.Video;

export namespace JobCreateRequest {
    export interface Image extends SegmentationAPI.ImageJobCreateRequest {
        type: "image";
    }

    export interface Video extends SegmentationAPI.VideoJobCreateRequest {
        type: "video";
    }
}
