// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export type JobCreateRequest = SegmentationApi.JobCreateRequest.Image | SegmentationApi.JobCreateRequest.Video;

export namespace JobCreateRequest {
    export interface Image extends SegmentationApi.ImageJobCreateRequest {
        type: "image";
    }

    export interface Video extends SegmentationApi.VideoJobCreateRequest {
        type: "video";
    }
}
