// This file was auto-generated by Fern from our API Definition.

export interface JobDownloadResponse {
    jobId: string;
    status: JobDownloadResponse.Status;
    expiresAt: string | null;
    downloadUrl: string | null;
    retryAfterSeconds: number | null;
    error: string | null;
}

export namespace JobDownloadResponse {
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Ready: "ready",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
