// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export interface JobListResponse {
    items: SegmentationAPI.JobSummary[];
    nextToken: string | null;
}
