// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface JobListResponse {
    items: SegmentationApi.JobSummary[];
    nextToken: string | null;
}
