// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export interface JobResultResponse {
    manifest: SegmentationAPI.OutputManifest;
    assets: SegmentationAPI.ResultAsset[];
    expiresIn: number;
}
