// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface JobResultResponse {
    manifest: SegmentationApi.OutputManifest;
    assets: SegmentationApi.ResultAsset[];
    expiresIn: number;
}
