// This file was auto-generated by Fern from our API Definition.

export const JobStatus = {
    Queued: "queued",
    Processing: "processing",
    Success: "success",
    Failed: "failed",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
