// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface JobSummary {
    jobId: string;
    type: JobSummary.Type;
    processingMode: SegmentationApi.ProcessingMode;
    totalItems: number;
    status: SegmentationApi.JobStatus;
    createdAt: string;
    updatedAt: string;
    error?: (string | null) | undefined;
}

export namespace JobSummary {
    export const Type = {
        Image: "image",
        Video: "video",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
