// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export interface JobTaskStatus {
    taskId: string;
    status: SegmentationAPI.JobStatus;
    error?: (string | null) | undefined;
}
