// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface JobTaskStatus {
    taskId: string;
    status: SegmentationApi.JobStatus;
    error?: (string | null) | undefined;
}
