// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationAPI from "../index.js";

export type OutputManifest = SegmentationAPI.OutputManifest.Image | SegmentationAPI.OutputManifest.Video;

export namespace OutputManifest {
    export interface Image extends SegmentationAPI.ImageOutputManifest {
        type: "image";
    }

    export interface Video extends SegmentationAPI.VideoOutputManifest {
        type: "video";
    }
}
