// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export type OutputManifest = SegmentationApi.OutputManifest.Image | SegmentationApi.OutputManifest.Video;

export namespace OutputManifest {
    export interface Image extends SegmentationApi.ImageOutputManifest {
        type: "image";
    }

    export interface Video extends SegmentationApi.VideoOutputManifest {
        type: "video";
    }
}
