// This file was auto-generated by Fern from our API Definition.

export const ProcessingMode = {
    Single: "single",
    Batch: "batch",
    Video: "video",
} as const;
export type ProcessingMode = (typeof ProcessingMode)[keyof typeof ProcessingMode];
