// This file was auto-generated by Fern from our API Definition.

export interface TrialOverview {
    offerVersion: string;
    status: TrialOverview.Status;
    grantTokens: number;
    consumedTokens: number;
    remainingTokens: number;
    durationDays: number;
    startedAt: string | null;
    expiresAt: string | null;
    activeJobId: string | null;
}

export namespace TrialOverview {
    export const Status = {
        Eligible: "eligible",
        Active: "active",
        Exhausted: "exhausted",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
