// This file was auto-generated by Fern from our API Definition.

export interface VideoJobCreateRequest {
    prompts: string[];
    /** When true, includes a baked preview video in the result. */
    generatePreview?: boolean | undefined;
    /** Confidence threshold. Defaults to 0. */
    scoreThreshold?: number | undefined;
    /** Sampling rate in frames per second. Mutually exclusive with numFrames. */
    fps?: number | undefined;
    /** Number of frames to sample. Mutually exclusive with fps. */
    numFrames?: number | undefined;
    /** Upper bound on processed video frames. */
    maxFrames?: number | undefined;
    /** Single task id returned by POST /v1/uploads/presign. */
    tasks: string[];
}
