// This file was auto-generated by Fern from our API Definition.

import type * as SegmentationApi from "../index.js";

export interface VideoOutputItem {
    taskId: string;
    inputId: string;
    units: number;
    generatedAt: string;
    previewUrl?: string | undefined;
    masks: string;
    fps?: number | undefined;
    numFrames?: number | undefined;
    maxFrames?: number | undefined;
    scoreThreshold: number;
    counts: SegmentationApi.VideoOutputCounts;
}
