// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contentType: "image/png"
 *     }
 */
export interface PresignUploadRequest {
    /** An image or video MIME type, or application/octet-stream. */
    contentType: string;
}
