// This file was auto-generated by Fern from our API Definition.

import * as SegmentationAPI from "../../src/api/index";
import { SegmentationAPIClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AccountClient", () => {
    test("getAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountId: "accountId",
            email: "email",
            emailVerified: true,
            image: "image",
            name: "name",
            status: "status",
        };

        server.mockEndpoint().get("/v1/account").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.account.getAccount();
        expect(response).toEqual(rawResponseBody);
    });

    test("getAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/account").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.account.getAccount();
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("getAccountOverview (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            tokenUsageLast24h: 1,
            billing: {
                accessStatus: "accessStatus",
                currentPeriodEnd: "currentPeriodEnd",
                latestInvoiceStatus: "latestInvoiceStatus",
                stripeSubscriptionStatus: "stripeSubscriptionStatus",
            },
            access: {
                mode: "paid",
                reason: "paid_access",
                canCreateJobs: true,
                videoAllowed: true,
                downloadsAllowed: true,
                maxImageTasksPerJob: 1,
                maxActiveJobs: 1,
            },
            trial: {
                offerVersion: "offerVersion",
                status: "eligible",
                grantTokens: 1,
                consumedTokens: 1,
                remainingTokens: 1,
                durationDays: 1,
                startedAt: "2024-01-15T09:30:00Z",
                expiresAt: "2024-01-15T09:30:00Z",
                activeJobId: "activeJobId",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/account/overview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.account.getAccountOverview();
        expect(response).toEqual(rawResponseBody);
    });

    test("getAccountOverview (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/account/overview")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.account.getAccountOverview();
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });
});
