// This file was auto-generated by Fern from our API Definition.

import * as SegmentationAPI from "../../src/api/index";
import { SegmentationAPIClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeysClient", () => {
    test("listApiKeys (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    keyId: "keyId",
                    label: "label",
                    prefix: "prefix",
                    revoked: true,
                    revokedAt: "revokedAt",
                    createdAt: "createdAt",
                    updatedAt: "updatedAt",
                },
            ],
        };

        server.mockEndpoint().get("/v1/api-keys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.listApiKeys();
        expect(response).toEqual(rawResponseBody);
    });

    test("listApiKeys (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/api-keys").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.listApiKeys();
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("createApiKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { label: "label" };
        const rawResponseBody = {
            apiKey: {
                keyId: "keyId",
                label: "label",
                prefix: "prefix",
                revoked: true,
                revokedAt: "revokedAt",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
            secret: "secret",
            secretUnavailable: true,
        };

        server
            .mockEndpoint()
            .post("/v1/api-keys")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.createApiKey({
            "Idempotency-Key": "Idempotency-Key",
            label: "label",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createApiKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { label: "x" };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/api-keys")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.createApiKey({
                "Idempotency-Key": "idempotencyKey",
                label: "x",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("revokeApiKey (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            apiKey: {
                keyId: "keyId",
                label: "label",
                prefix: "prefix",
                revoked: true,
                revokedAt: "revokedAt",
                createdAt: "createdAt",
                updatedAt: "updatedAt",
            },
        };

        server
            .mockEndpoint()
            .delete("/v1/api-keys/keyId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.revokeApiKey({
            keyId: "keyId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeApiKey (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .delete("/v1/api-keys/keyId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.revokeApiKey({
                keyId: "keyId",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });
});
