// This file was auto-generated by Fern from our API Definition.

import * as SegmentationApi from "../../src/api/index";
import { SegmentationApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingClient", () => {
    test("createCheckout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/v1/billing/checkout")
            .header("Idempotency-Key", "Idempotency-Key")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.createCheckout({
            "Idempotency-Key": "Idempotency-Key",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createCheckout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/billing/checkout")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.createCheckout({
                "Idempotency-Key": "idempotencyKey",
            });
        }).rejects.toThrow(SegmentationApi.UnauthorizedError);
    });

    test("createBillingPortal (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/v1/billing/portal")
            .header("Idempotency-Key", "Idempotency-Key")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.createBillingPortal({
            "Idempotency-Key": "Idempotency-Key",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createBillingPortal (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationApiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/billing/portal")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.createBillingPortal({
                "Idempotency-Key": "idempotencyKey",
            });
        }).rejects.toThrow(SegmentationApi.UnauthorizedError);
    });
});
