// This file was auto-generated by Fern from our API Definition.

import * as SegmentationAPI from "../../src/api/index";
import { SegmentationAPIClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("listJobs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    jobId: "job-abc-987",
                    type: "image",
                    processingMode: "batch",
                    totalItems: 2,
                    status: "processing",
                    createdAt: "2026-03-07T12:00:00Z",
                    updatedAt: "2026-03-07T12:01:00Z",
                    error: "error",
                },
            ],
            nextToken: "eyJvZmZzZXQiOjIwfQ==",
        };

        server.mockEndpoint().get("/v1/jobs").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.listJobs();
        expect(response).toEqual(rawResponseBody);
    });

    test("listJobs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobs();
        }).rejects.toThrow(SegmentationAPI.BadRequestError);
    });

    test("listJobs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobs();
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("listJobs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.listJobs();
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });

    test("createJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "image",
            prompts: ["prompts"],
            tasks: ["a1b2c3d4-e5f6-7890-abcd-ef1234567890.png", "b2c3d4e5-f6a7-8901-bcde-f12345678901.jpg"],
        };
        const rawResponseBody = {
            jobId: "job-abc-987",
            type: "image",
            totalItems: 2,
            trial: { remainingTokens: 1, expiresAt: "2024-01-15T09:30:00Z" },
        };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.createJob({
            type: "image",
            prompts: ["prompts"],
            tasks: ["a1b2c3d4-e5f6-7890-abcd-ef1234567890.png", "b2c3d4e5-f6a7-8901-bcde-f12345678901.jpg"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.BadRequestError);
    });

    test("createJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("createJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.PaymentRequiredError);
    });

    test("createJob (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.ForbiddenError);
    });

    test("createJob (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.ConflictError);
    });

    test("createJob (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });

    test("createJob (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.BadGatewayError);
    });

    test("createJob (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { type: "image", prompts: ["prompts", "prompts"], tasks: ["tasks", "tasks"] };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                type: "image",
                prompts: ["prompts", "prompts"],
                tasks: ["tasks", "tasks"],
            });
        }).rejects.toThrow(SegmentationAPI.ServiceUnavailableError);
    });

    test("retrieveJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            jobId: "job-abc-987",
            type: "image",
            processingMode: "batch",
            status: "processing",
            totalItems: 2,
            createdAt: "2026-08-03T12:00:00Z",
            updatedAt: "2026-08-03T12:01:00Z",
            error: "error",
            tasks: [
                { taskId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890.png", status: "processing", error: "error" },
                { taskId: "b2c3d4e5-f6a7-8901-bcde-f12345678901.jpg", status: "success", error: "error" },
            ],
        };

        server.mockEndpoint().get("/v1/jobs/jobId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.retrieveJob({
            jobId: "jobId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieveJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs/jobId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.retrieveJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("retrieveJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs/jobId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.retrieveJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.NotFoundError);
    });

    test("retrieveJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server.mockEndpoint().get("/v1/jobs/jobId").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.retrieveJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });

    test("retrieveJobResult (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            manifest: {
                type: "image",
                jobId: "jobId",
                prompts: ["prompts"],
                items: [
                    {
                        taskId: "taskId",
                        inputId: "inputId",
                        units: 1,
                        generatedAt: "2024-01-15T09:30:00Z",
                        masks: [{ maskIndex: 1, confidence: 1.1, url: "url" }],
                    },
                ],
            },
            assets: [{ key: "key", url: "url" }],
            expiresIn: 1,
        };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/result")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.retrieveJobResult({
            jobId: "jobId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieveJobResult (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/result")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("retrieveJobResult (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/result")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.NotFoundError);
    });

    test("retrieveJobResult (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/result")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.ConflictError);
    });

    test("retrieveJobResult (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/result")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });

    test("retrieveJobDownload (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            jobId: "jobId",
            status: "pending",
            expiresAt: "2024-01-15T09:30:00Z",
            downloadUrl: "downloadUrl",
            retryAfterSeconds: 1,
            error: "error",
        };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.retrieveJobDownload({
            jobId: "jobId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("retrieveJobDownload (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("retrieveJobDownload (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.NotFoundError);
    });

    test("retrieveJobDownload (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.ConflictError);
    });

    test("retrieveJobDownload (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.retrieveJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });

    test("createJobDownload (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            jobId: "jobId",
            status: "pending",
            expiresAt: "2024-01-15T09:30:00Z",
            downloadUrl: "downloadUrl",
            retryAfterSeconds: 1,
            error: "error",
        };

        server
            .mockEndpoint()
            .post("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.createJobDownload({
            jobId: "jobId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createJobDownload (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("createJobDownload (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.NotFoundError);
    });

    test("createJobDownload (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.ConflictError);
    });

    test("createJobDownload (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/jobs/jobId/download")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJobDownload({
                jobId: "jobId",
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });
});
