// This file was auto-generated by Fern from our API Definition.

import * as SegmentationAPI from "../../src/api/index";
import { SegmentationAPIClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UploadsClient", () => {
    test("createUploadPresign (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { contentType: "image/png" };
        const rawResponseBody = {
            uploadUrl: "uploadUrl",
            taskId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890.png",
            bucket: "bucket",
            expiresIn: 1,
        };

        server
            .mockEndpoint()
            .post("/v1/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.uploads.createUploadPresign({
            contentType: "image/png",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createUploadPresign (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { contentType: "contentType" };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.uploads.createUploadPresign({
                contentType: "contentType",
            });
        }).rejects.toThrow(SegmentationAPI.BadRequestError);
    });

    test("createUploadPresign (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { contentType: "contentType" };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.uploads.createUploadPresign({
                contentType: "contentType",
            });
        }).rejects.toThrow(SegmentationAPI.UnauthorizedError);
    });

    test("createUploadPresign (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new SegmentationAPIClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { contentType: "contentType" };
        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .post("/v1/uploads/presign")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.uploads.createUploadPresign({
                contentType: "contentType",
            });
        }).rejects.toThrow(SegmentationAPI.InternalServerError);
    });
});
