// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { ApiKeysClient } from "./api/resources/apiKeys/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { JobsClient } from "./api/resources/jobs/client/Client.js";
import { UploadsClient } from "./api/resources/uploads/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace SegmentationAPIClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SegmentationAPIClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SegmentationAPIClient.Options>;
    protected _uploads: UploadsClient | undefined;
    protected _jobs: JobsClient | undefined;
    protected _account: AccountClient | undefined;
    protected _apiKeys: ApiKeysClient | undefined;
    protected _billing: BillingClient | undefined;

    constructor(options: SegmentationAPIClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get uploads(): UploadsClient {
        return (this._uploads ??= new UploadsClient(this._options));
    }

    public get jobs(): JobsClient {
        return (this._jobs ??= new JobsClient(this._options));
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get apiKeys(): ApiKeysClient {
        return (this._apiKeys ??= new ApiKeysClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
