// This file was auto-generated by Fern from our API Definition.

export const SegmentationAPIEnvironment = {
    Default: "https://api.segmentationapi.com",
} as const;

export type SegmentationAPIEnvironment = typeof SegmentationAPIEnvironment.Default;
