// This file was auto-generated by Fern from our API Definition.

export const SegmentationApiEnvironment = {
    Default: "https://api.segmentationapi.com",
} as const;

export type SegmentationApiEnvironment = typeof SegmentationApiEnvironment.Default;
